# Generated by Django 4.0.2 on 2022-03-03 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOfVisit', models.DateTimeField(auto_now_add=True)),
                ('storeName', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('placeId', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(through='recipes.IngredientRecipeUnit', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='unit',
            name='recipes',
            field=models.ManyToManyField(through='recipes.IngredientRecipeUnit', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipeunit',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipeunit',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipeunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='recipes.unit'),
        ),
    ]
